### ISSUE TITLE
running ProteoDisco::incorporateGenomicVariants on hg38

### ISSUE THREAD

**Issue by StephenLi55** [ErasmusMC-CCBC/ProteoDisco#4]
Hi,

  I am trying to generate a list of mutant transcript from my vcf file (aligned with hg38), using the following command : 
"
ProteoDiscography.hg38 <- ProteoDisco::generateProteoDiscography(
  TxDb = TxDb.Hsapiens.UCSC.hg38.knownGene::TxDb.Hsapiens.UCSC.hg38.knownGene, 
  genomeSeqs = BSgenome.Hsapiens.UCSC.hg38::BSgenome.Hsapiens.UCSC.hg38
)

ProteoDiscography.hg38 <- ProteoDisco::importGenomicVariants(
  ProteoDiscography = ProteoDiscography.hg38,
  files = "Custom protein database/D0_1_1.fq.vcf",
  samplenames = 'D0_1_1.fq',
  threads = 1, 
  performAnchorCheck = FALSE
)

ProteoDiscography.hg38 <- ProteoDisco::incorporateGenomicVariants(
  ProteoDiscography = ProteoDiscography.hg38,
  aggregateSamples = FALSE, 
  aggregateWithinExon = TRUE, 
  aggregateWithinTranscript = TRUE, 
  ignoreOverlappingMutations = TRUE, 
  threads = 1
)
"

However, the incorporateGenomicVariants step resulted in the following error message : 
"
2022-09-20 10:44:34	CDSID #204904 has 3 position-overlapping genomic mutations within the exon, only incorporating the first of these mutations based on the input order.

Error: BiocParallel errors
  1 remote errors, element index: 5042
  6656 unevaluated and other errors
  first remote error:
Error in .Call2("C_solve_user_SEW", refwidths, start, end, width, translate.negative.coord, : solving row 1: 'allow.nonnarrowing' is FALSE and the supplied start (20) is > refwidth + 1
"

Seems like it is caused by issue with the annotated coding regions coordinates. Is it due to the choice of the TxDB and the genome sequence?

 best wishes,

  Stephen

**Comment by HarmenvdWerken** [comment]
Dear Stephen,

We cannot directly understand/fix the problem. Could you share the vcf files with us? You can send it to h.vandewerken[at]erasmusmc.nl

All the best,
Harmen van de Werken

**Comment by wvandegeer** [comment]
Thank you, Stephen. There was a very specific case with an intron-exon spanning InDel that was causing some trouble. We've fixed the problem and it should be running smoothly now.

Hope you find some interesting mutant transcripts!

**Comment by gowgowuk** [comment]
Hello, sorry to revive an old closed issue, but as I have a very similar error, I thought I would post it here.
I am trying to run the package on the mouse genome (GRCm39).
Here is my error:
Error: BiocParallel errors
  1 remote errors, element index: 775
  16136 unevaluated and other errors
  first remote error:
Error in .Call2("C_solve_user_SEW", refwidths, start, end, width, translate.negative.coord, : solving row 1: 'allow.nonnarrowing' is FALSE and the supplied start (4) is > refwidth + 1

Which looks remarkably similar to the above.

the script is below. My vcf file is too big to attach here

Many Thanks!
All the best,

Philippe

annot<-c("Mus_musculus.gencode.vM35.annotation.chr.gtf")
genome<-c("GRCm39.primary_assembly.genome.chr.fa.gz")
TxDb <- GenomicFeatures::makeTxDbFromGFF(file = annot)
genomeSeqs <- Biostrings::readDNAStringSet(filepath = genome, format = 'fasta')
names(genomeSeqs) <- gsub(' .*', '', names(genomeSeqs))
ProteoDiscography <- ProteoDisco::generateProteoDiscography(TxDb = TxDb, genomeSeqs = genomeSeqs, geneticCode = 'Standard' )
vcffile <- c("DMSO_24hr_1_chr_chromonly.vcf")
ProteoDiscography <- ProteoDisco::importGenomicVariants(ProteoDiscography = ProteoDiscography,files = vcffile,performAnchorCheck = FALSE,samplenames = 'DMSO_24hr_1')

ProteoDiscography <- ProteoDisco::incorporateGenomicVariants(
  ProteoDiscography = ProteoDiscography,
  aggregateSamples = FALSE, 
  aggregateWithinExon = TRUE, 
  aggregateWithinTranscript = TRUE, 
  ignoreOverlappingMutations = TRUE, 
  threads = 4
)
