### ISSUE TITLE
distanceAssignedCDS and distanceSJtoCDS conflict

### ISSUE THREAD

**Issue by 1813805349** [ErasmusMC-CCBC/ProteoDisco#6]
Hi,
I'm confused about cryptic CDS.
In the first part of the code, cryptic CDS condition(distanceAssignedCDS > maxDistance), but in the latter part of the code, distanceSJtoCDS <=maxDistance.Because distanceSJtoCDS >maxDistance, distanceSJtoCDS must also be greater than maxDistance.So protein sequences cannot be generated.
first part
![image](https://user-images.githubusercontent.com/87262903/200521759-fda2b726-3898-4a70-992d-cba0c1a1bdfa.png)
latter part
![image](https://user-images.githubusercontent.com/87262903/200521783-3e6d69b7-11fb-42a2-923e-54e26d57172c.png)
![image](https://user-images.githubusercontent.com/87262903/200521801-0f366052-81aa-4b40-92e4-189df464576f.png)

**Comment by J0bbie** [comment]
You're absolutely right. This must have slipped by during testing..
I've removed the second condition (distanceSJtoCDS <=maxDistance) which indeed would always be the inverse of the prior condition.

Hope this now gives you some interesting results!
